### ISSUE TITLE
Webmail settings problem

### ISSUE THREAD

**Issue by andreavarsa** [VTECRM/vtenext#1]
when I try to set email account in webmail module the popup closes after the first click and redirect to the home page.
![shot](https://user-images.githubusercontent.com/30125592/28132035-f47ddb76-673b-11e7-836e-a87d200b0015.png)

**Comment by manueltag** [comment]
Hi Andrea. Which browser and operating system do you use? The problem, as i can see from image, is that the popup is under the layer (wrong z-index) and when you click on the semi-transparent layer it closes the popup. Is the problem persists in the other browser too?

**Comment by denisdal** [comment]
Also, please make sure that you have php5-imap installed end activated

**Comment by andreavarsa** [comment]
I use Chromium with ubuntu and it works with firefox

**Comment by manueltag** [comment]
What version of Ubuntu do you use?

**Comment by manueltag** [comment]
Hi Andrea, I test it on Ubuntu 14.04 (32 bit) v. 59.0.3071.109 (build) and it works. What version of Chromium do you use?

**Comment by andreavarsa** [comment]
These are my os and chromium version:
Version 59.0.3071.109 (Build) Built on Ubuntu , running on Ubuntu 16.04 (a 64 bit)
