### ISSUE TITLE
PHP versions

### ISSUE THREAD

**Issue by pauceano** [VTECRM/vtenext#10]
I am trying to install VTNEXT in the web web server of my Internet provider. I am trying different versions of PHP but in each of them I have different problems.
My first question would be, what is the PHP version preferred.
I have seen that there are to options that my PHP configuration panel does not let me change (I have no acces to the PHP.ini, so I use a panel from my provider) and the installer complains about them (the most important is mod_rewrite wich I do not have in the panel of any of PHP versions). But the options I have access to change with PHP version, so I would like to choose first the best PHP version and  go from there.

Thanks.

**Comment by pauceano** [comment]
The installation seems to run ok with 5.6 even if I get a lot of messages like:
Notice: Undefined variable: _SESSION in /home/popkeoco/public_html/source/vteversion.php on line 18

Notice: Undefined index: enterprise_project in /home/popkeoco/public_html/source/vteversion.php on line 18

Notice: Use of undefined constant self - assumed 'self' in /home/popkeoco/public_html/source/include/BaseClasses.php on line 70

Notice: Use of undefined constant parent - assumed 'parent' in /home/popkeoco/public_html/source/include/BaseClasses.php on line 78

Strict Standards: Only variables should be assigned by reference in /home/popkeoco/public_html/source/include/database/PearDatabase.php on line 22

Strict Standards: Only variables should be assigned by reference in /home/popkeoco/public_html/source/include/database/PearDatabase.php on line 23
...
But, once finished (I can see in mySQL that the tables are generated), index.php generates only tis warinng/error messages, and I get no user interface.

**Comment by danieletonani** [comment]
You should disable "E_NOTICE" in the error_reporting of php setup as suggested by the installer.

**Comment by pauceano** [comment]
Dissablin only E_NOTICE I still get a bunch of messages:

**Comment by pauceano** [comment]
Dissabling E_NOTICE I also get a bunch of messages
Dissabling ALL messages I do not get any message, but I am not sure if this is the way, is it?

Strict Standards: Only variables should be assigned by reference in /home/popkeoco/public_html/vt/include/database/PearDatabase.php on line 22

Strict Standards: Only variables should be assigned by reference in /home/popkeoco/public_html/vt/include/database/PearDatabase.php on line 23

Strict Standards: Only variables should be assigned by reference in /home/popkeoco/public_html/vt/include/database/PearDatabase.php on line 1172

Strict Standards: Only variables should be assigned by reference in /home/popkeoco/public_html/vt/include/database/PearDatabase.php on line 217

Strict Standards: Only variables should be assigned by reference in /home/popkeoco/public_html/vt/include/database/PearDatabase.php on line 217

Strict Standards: Only variables should be assigned by reference in /home/popkeoco/public_html/vt/include/database/PearDatabase.php on line 217

Strict Standards: Declaration of TmpUserModTables::generateTmpForUser() should be compatible with TmpUserTables::generateTmpForUser($userid, $moduleHint = 'Accounts') in /home/popkeoco/public_html/vt/include/utils/TempTables.php on line 0

Strict Standards: Declaration of TmpUserModTables::hasSubUser() should be compatible with TmpUserTables::hasSubUser($userid, $subuserid) in /home/popkeoco/public_html/vt/include/utils/TempTables.php on line 0

Strict Standards: Non-static method SDK::getUtils() should not be called statically in /home/popkeoco/public_html/vt/include/Webservices/Utils.php on line 16

Strict Standards: Non-static method SDK::getUtilsList() should not be called statically in /home/popkeoco/public_html/vt/modules/SDK/SDK.php on line 525

Strict Standards: Declaration of Documents::generateReportsQuery() should be compatible with CRMEntityBase::generateReportsQuery($module, $reportid = 0, $joinProducts = false) in /home/popkeoco/public_html/vt/modules/Documents/Documents.php on line 21

Strict Standards: Declaration of HelpDesk::process_list_query() should be compatible with CRMEntityBase::process_list_query($query, $row_offset, $limit = -1, $max_per_page = -1) in /home/popkeoco/public_html/vt/modules/HelpDesk/HelpDesk.php on line 0

Strict Standards: Declaration of HelpDesk::save_related_module() should be compatible with CRMEntityBase::save_related_module($module, $crmid, $with_module, $with_crmid, $skip_check = false) in /home/popkeoco/public_html/vt/modules/HelpDesk/HelpDesk.php on line

**Comment by pauceano** [comment]
Diabling ALL messages, after the installation I get a blank screen. I can reload to the index and things seem to work in the backend area, but my user interface looks like lacking CSS (no formats).

**Comment by danieletonani** [comment]
You should use this configuration with your php version:
error_reporting = E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_STRICT

**Comment by pauceano** [comment]
Thanks.
Yes, I understand it, but I do not have access to ini files, I have to configure PHP options in a panel, and I only have these options:
~E_ALL
E_ALL & ~E_NOTICE
E_ALL
So I cannot define error_reporting as recomended. As my only option to get rid of the unwanted messages is dissable totally, my question was which of the messages I am getting are actual errors. Because if I define ~E_ALL it does not work well.

**Comment by pauceano** [comment]
The total list of messages I get with E_ALL & ~E_NOTICE, after apparently successfull instalation, is this html (I changed the extension to TXT to be able to upload here).

:
[VTENEXTCE 17.07.txt](https://github.com/VTECRM/vtenext/files/1270057/VTENEXTCE.17.07.txt)

**Comment by pauceano** [comment]
Ok, I called the function error_reporting(E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_STRICT); in index.php (which I hope overrides PHP.ini settings), and now I have no messages, nor even the warnings that probably where caused by the previous messages.
