### ISSUE TITLE
Storage deduplication

### ISSUE THREAD

**Issue by Pe46dro** [VTECRM/vtenext#10]
Hi, i use your software from 2016 and I think that the table `_attachments` can be improved.
The new insert/update workflow should be something like this:

1. Calculate hash file before insert or update
2. If there is already a document with same hash , document can be "deduplicated" only the relation is needed on `_seattachmentsrel`
3. Storage space needed will be reduced
4. Profit!

The implementation should be not sto hard and not too much time consuming for recovery of previous lines.
On our installation i made some script to check the reduction rate and we are around 33% of stored data reduction.

**Comment by millenium-codebug** [comment]
Great suggestion, i suggested a similar implementation on #2 for messages

**Comment by manueltag** [comment]
Hi @Pe46dro, thanks for the report. We have opened an internal request to the development department.
