### ISSUE TITLE
Create Workflows

### ISSUE THREAD

**Issue by pauceano** [VTECRM/vtenext#13]
When I try to create a workflow clicking "NEW WORKFLOW" in "Workflow list" always appears a modal popup saying "Failure:undefined"

**Comment by manuelemaporti** [comment]
Can you give me a screenshot? You can use Process manager in order to create more powerful workflows.

**Comment by pauceano** [comment]
Thanks, I still do not fully understand Process manager, I was testing and trying to learn about workflows. I get this error when trying to make a new workflow
![aaaa](https://user-images.githubusercontent.com/5346355/30266092-9bb6e956-96de-11e7-94d3-f18cdeca8aaf.png)
