### ISSUE TITLE
Installing a custom module

### ISSUE THREAD

**Issue by pauceano** [VTECRM/vtenext#14]
Onces the custom model is defined, when trying to instal I get "The directory vtlib/ModuleDir/17.07 is not readable" Checking the folders I see that inside  vtlib/ModuleDir there are the following folders:
5.0, 5.1, 15.05, 15.10 and 16.09.
Is there anyway to create the new on? Have I jumped an step? can I create it somehow manually (maybe copying the last one)?

**Comment by manuelemaporti** [comment]
The folders 5.0, 5.1, 15.05, 15.10 and 16.09 are the models for the creation of modules in the previous versions of vte. You just need the folder 17.07.

**Comment by pauceano** [comment]
Thanks, I understood that, but I do not have the 17.07, how can I make it?

**Comment by manuelemaporti** [comment]
Your version is the $enterprise_current_version in vteversion.php so 17.07

**Comment by pauceano** [comment]
Yes, but the folder is not there. How can I get this folder? should I copy it from previous version?

**Comment by manuelemaporti** [comment]
ok now I understand. Copy the folder 16.09 and rename into 17.07

**Comment by marcogerm** [comment]
thank you, so I resolved. Now, however, there is another problem, I follow the creation process, I click on install but there is only one page refresh without installing the module

**Comment by manuelemaporti** [comment]
you have to edit the file modules/Settings/ModuleMakerGenerator.php on line 428 replacing
`require('vteversion');`
with
`require('vteversion.php');`

**Comment by marcogerm** [comment]
Fixed, but the file is in this path modules / Settings / ModuleMaker and the modified line is 855
