### ISSUE TITLE
Problem Open Mail and Folders Mailbox

### ISSUE THREAD

**Issue by mmartinitesyr** [VTECRM/vtenext#19]
When i go to Message Module for Read the new e-mail when i click on new e-mail, the crm remaining in loading state for ever 
if i close the message module and it re-open i find the same e-mail marked as readed and this is selectable for view

if i go on mailbox folders the all folders is empty.

the crm sent correctly the e-mails and receive. the cronjob Runcron.sh work correctly

I have:
ubuntu  14.04 LTS
PHP V 5.5.9
Mysql  Ver 14.14 Distrib 5.5.57

![immagine](https://user-images.githubusercontent.com/32962206/31829412-747d73f2-b5bd-11e7-9c77-462ffd7a22e1.png)

**Comment by IntegrysIT** [comment]
I think this issue could be merged with mine : #18
 https://github.com/VTECRM/vtenext/issues/18

**Comment by mmartinitesyr** [comment]
Yes approved.

**Comment by centoasa** [comment]
For me too

**Comment by davidegiarolo** [comment]
does those emails contain attachments? some mail servers have a bad inline attachment management

**Comment by centoasa** [comment]
no, email doesn't have attachment

**Comment by centoasa** [comment]
maybe max_execution_time on php setting? what's the best settings for VTE?

**Comment by mmartinitesyr** [comment]
yes confirm, in my case im not have the attachment.
