### ISSUE TITLE
VTENEXT CE from old version

### ISSUE THREAD

**Issue by andreavergo** [VTECRM/vtenext#2]
Goodmorning,
it's possible upgrade from VTE 15.10 (or old version) to VTENEXT CE

Thanks all

**Comment by davidegiarolo** [comment]
Hi,
at the moment VTECRM doesn't have an upgrade process that let it go to VTENEXT. But you can still use 15.10 version in the meantime and give a try or start new projects with the VTENEXT CE. 
In that way we can track the issues in these weeks and then work to give the update script that point to a very stable version like the 15.10 was for example.
regards
short version: 4-6 weeks and we release the upgrade script

**Comment by andreavergo** [comment]
Hi @davidegiarolo,
now it's possibile upgrade from old version?
Regards
