### ISSUE TITLE
delete email button don't work

### ISSUE THREAD

**Issue by centoasa** [VTECRM/vtenext#20]
VTEnextCE 17.07
![schermata 2017-11-14 alle 13 08 49](https://user-images.githubusercontent.com/5500935/32779190-0b1b356e-c93d-11e7-83b6-ae0f77fc4f62.png)
the button does not work, simply, do nothing!

**Comment by davidegiarolo** [comment]
if the trash folder is correctly configured may be the problem is related to the same timeout yo have on issue #19

**Comment by centoasa** [comment]
trash folder settings properly. I think same issue timeout as in #19

**Comment by centoasa** [comment]
If  I open the email on other tab of browser, the delete button works well.
