### ISSUE TITLE
edit/update email template

### ISSUE THREAD

**Issue by centoasa** [VTECRM/vtenext#22]
How can I edit/update all the email template?
Where I can found them?

**Comment by davidegiarolo** [comment]
you can find them in the system setting under the customer tools menù entry

**Comment by centoasa** [comment]
I mean the system email, as the email to ticket updates...
Gentile Remigio Ruberto,

C`e` una risposta a test problema ticketnel Portale Clienti di Puoi usare il seguente link per visualizzare le risposte date:
Dettaglio ticket

Grazie

Team di supporto
