### ISSUE TITLE
email list

### ISSUE THREAD

**Issue by centoasa** [VTECRM/vtenext#23]
from what date are the emails from imap taken?
because now I see the oldest my email is 31-10-17
how long are emails taken and updated by imap? is there a setting where I can set this time?

**Comment by manuelemaporti** [comment]
Hello, did you enable the cron? You have to put in your crontab this:
`*/1 *  * * *    root    YOUR_VTE_ABSOLUTE_PATH/cron/RunCron.sh >> YOUR_VTE_ABSOLUTE_PATH/logs/cron.log 2>&1`

When you configure a new account or if you force the sync:
![image](https://user-images.githubusercontent.com/29864701/32937879-82b3c07a-cb7a-11e7-8f30-66f5d7bb0f1b.png)
the cron download all the messages of you mail account.
Then it sync only last 15 days.

So I suggest you to enable cron and force the sync.
