### ISSUE TITLE
cron

### ISSUE THREAD

**Issue by centoasa** [VTECRM/vtenext#24]
In config.cron.php I've address the app key (taken from config.inc.php)
If into my channel I add the cron as 
root /home/irnndaeb/vte.100asa.it/cron/RunCron.sh >> /home/irnndaeb/vte.100asa.it/logs/cron.log 2>&1
cron.log says: Status: 404 Not Found
X-Powered-By: PHP/7.0.25
Content-type: text/html; charset=UTF-8

No input file specified.
/bin/bash: root: command not found
/bin/bash: root: command not found

what's the problem?

**Comment by manueltag** [comment]
Hi, you should configure the system crontab like this:

*/1 * * * * root /home/irnndaeb/vte.100asa.it/cron/RunCron.sh >> /home/irnndaeb/vte.100asa.it/logs/cron.log 2>&1

**Comment by centoasa** [comment]
Yes sure, it was implied by cron's time
but logs is always the same
I've cpanel (if this may help for understanding issue)

**Comment by manueltag** [comment]
If you use cpanel you have only to insert the script path without user (in your case root).
Es. /home/irnndaeb/vte.100asa.it/cron/RunCron.sh >> /home/irnndaeb/vte.100asa.it/logs/cron.log 2>&1

**Comment by centoasa** [comment]
always Access denied!

**Comment by manueltag** [comment]
The command is ok now. You can try with this command:
/home/irnndaeb/vte.100asa.it/cron/RunCron.sh app_key=your_app_key >> /home/irnndaeb/vte.100asa.it/logs/cron.log 2>&1

If it doesn't work you can try with http command:
http://your.site.com/cron/RunCron.php?app_key=your_app_key

**Comment by centoasa** [comment]
web page is blank, and cron log is empty
