### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by centoasa** [VTECRM/vtenext#25]
All crm works well with php 7, but portal goes on error 500

**Comment by manueltag** [comment]
Hi, php7 is not supported. The portal doesn't work beacause the nusoap lib inside the portal supports only php < 7. You can update the nusoap library inside the portal folder and inside crm directory include/nusoap.

If it doesn't work you have to activate the error logs in portal/index.php with:

ini_set('display_errors', 'on');
error_reporting(E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED);

and show us the error.
