### ISSUE TITLE
missing characters

### ISSUE THREAD

**Issue by centoasa** [VTECRM/vtenext#26]
After latest fixing, there are on the left manu some missing characters
![schermata 2017-11-15 alle 13 11 17](https://user-images.githubusercontent.com/5500935/32835516-adcfdcc8-ca06-11e7-8e51-d18b495d0c66.png)

**Comment by manueltag** [comment]
Hi, have you try to delete the cache of the browser and login again into crm?

**Comment by centoasa** [comment]
already done, same issue
