### ISSUE TITLE
top-right icons layout in ProjectPlan (with Chrome)

### ISSUE THREAD

**Issue by IntegrysIT** [VTECRM/vtenext#29]
There are few layout problem with chrome.
One if this cause a problem with the right-most menu ,  let's me explain.

If you go to Project, then click/open a Project at the top-right , there is a menu (#Buttons_List_3) with Favorite+Notify+Edit+Link+Other.
With Firefox there's no problem.
With Chrome the icons are scraped around and the first item (Processes) of menu RELATIONS is not accesible, because it's covered.

Screenshots follow ...

![firefox](https://user-images.githubusercontent.com/32899531/32856285-a847ba26-ca44-11e7-9909-4f974bd7a0e0.png)
![chrome](https://user-images.githubusercontent.com/32899531/32856291-ac1002c6-ca44-11e7-9318-f3a900a9420e.png)

At your disposal for any question or test.

**Comment by centoasa** [comment]
Same as #28
