### ISSUE TITLE
Cant Pass Administration User Activation

### ISSUE THREAD

**Issue by Miccia94** [VTECRM/vtenext#3]
All browser are crashing after pressing Register at **http://crm/vtenext/modules/Morphsuit/RequestMorphsuit.php?morph_mode=installation**

**Comment by davidegiarolo** [comment]
Hi, which server environment are you using? please tell us more about you php configuration, thank you

**Comment by Miccia94** [comment]
Hello,
Apache:
Server version: Apache/2.4.25 (Ubuntu)
Server built:   2017-06-26T11:50:10

OS:
Ubuntu 17.04 (GNU/Linux 4.10.0-28-generic x86_64)

Mysql:
mysql  Ver 15.1 Distrib 10.1.22-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

Php:
https://hastebin.com/iqocopuqoy.makefile

I've passed all requirements over the installation step

**Comment by davidegiarolo** [comment]
ok we usually use lts versions of ubuntu (14.04server lts). give use some time to try on the 17.04 in the meantime consider to install in an lts environment to ensure updates and stability (for example also the 16.04 lts have some security problems weeks ago for that reason we use the 14.04 in production environment)
