### ISSUE TITLE
Project + Link + create a new TASK = waiting STUCK

### ISSUE THREAD

**Issue by IntegrysIT** [VTECRM/vtenext#30]
There is an error when I try to create a new TASK, while in LINK of a PROJECT.

Let me explain:
I go to PROJECTS, select an existing task, click to LINK, then click to CREATE  ... loading circle forever.
and in js-console there's this error 

ReferenceError: **toggleWorkingDays** is not defined
jquery.js%20line%202%20%3E%20eval:1:35
	<anonimo> http://172.20.21.42/include/js/jquery.js%20line%202%20%3E%20eval:1:35
	j http://172.20.21.42/include/js/jquery.js:2:27304
	add http://172.20.21.42/include/js/jquery.js:2:27618
	m.fn.ready http://172.20.21.42/include/js/jquery.js:2:29706
	<anonimo> http://172.20.21.42/include/js/jquery.js%20line%202%20%3E%20eval:1:1
	globalEval/< http://172.20.21.42/include/js/jquery.js:2:2615
	globalEval http://172.20.21.42/include/js/jquery.js:2:2589
	domManip http://172.20.21.42/include/js/jquery.js:4:23105
	append http://172.20.21.42/include/js/jquery.js:4:20615
	html/< http://172.20.21.42/include/js/jquery.js:4:22138
	m.access http://172.20.21.42/include/js/jquery.js:4:3397
	html http://172.20.21.42/include/js/jquery.js:4:21736
	success http://172.20.21.42/modules/Popup/Popup.js:290:5
	j http://172.20.21.42/include/js/jquery.js:2:27304
	fireWith http://172.20.21.42/include/js/jquery.js:2:28122
	x http://172.20.21.42/include/js/jquery.js:5:22109
	b http://172.20.21.42/include/js/jquery.js:5:26030

![firefox](https://user-images.githubusercontent.com/32899531/32857449-224dc2b8-ca48-11e7-9089-d0e6e29f1ac8.png)

I took a screencast, but cannot it attach here ... I put it on my gdrive
https://goo.gl/8w39pf

At your disposal for any question or test.

**Comment by centoasa** [comment]
Try with other template softed

**Comment by IntegrysIT** [comment]
How can I change template?
Can you point me to the right direction? 😒  please

**Comment by centoasa** [comment]
In your profile you can can the template

**Comment by centoasa** [comment]
In your profile you can change the template
