### ISSUE TITLE
Password recovery email from

### ISSUE THREAD

**Issue by centoasa** [VTECRM/vtenext#31]
Why password recovery email come from the email address of admin, instead from the system email of crm setting in config?

**Comment by davidegiarolo** [comment]
the email in settings is for authentication only on the smtp server, is never used by default

**Comment by centoasa** [comment]
I mean, also for portal password recovery, to use the system crm email address used in all others system emails.

**Comment by centoasa** [comment]
Sorry, I forgot, password recevery from portal.

**Comment by centoasa** [comment]
maybe the email come from the user who open the ticket?
