### ISSUE TITLE
Gestore chiamata

### ISSUE THREAD

**Issue by centoasa** [VTECRM/vtenext#32]
Scusatemi, ma perché se cerco di aggiungere un nuovo record a "gestore chiamata" mi compare "Questa Operazione non è al momento supportata"
Devo per forza collegare il modulo ad un pbx asterisk? Posso solo creare un promemoria per una chiamata in uscita?
Grazie

**Comment by denisdal** [comment]
Esatto, i record vengono automaticamente aggiunti in base alle telefonate in entrata/uscita che giungono dal server Asterisk.
Se dovete creare un promemoria su una chiamata potete creare un evento di calendario di tipo "Chiamata"
Grazie
