### ISSUE TITLE
PHP Version 7

### ISSUE THREAD

**Issue by Pomazan-Bogdan** [VTECRM/vtenext#4]
Subj?

**Comment by davidegiarolo** [comment]
Hello, can you please explain the question?

**Comment by Pomazan-Bogdan** [comment]
Sorry for my English.
I asked this question because PHP7 works noticeably faster, which is very noticeable on Shared Hosting or weak VPS.

Are you planning to do something in this direction?

And is there any roadmap for your future changes?
