### ISSUE TITLE
Apache and PHP configuration 

### ISSUE THREAD

**Issue by gillustrazione93** [VTECRM/vtenext#41]
Hello everyone.
is it possible to have the configuration for apache and php?
I'm having trouble installing on lamp server on ubuntu 14.04

**Comment by denisdal** [comment]
PHP Requirements:

- Version: PHP 5.3.x/5.4.x/5.5.x (5.6.x should work as well)
- Variables: short_open_tag = On , log_errors = On , error_reporting = E_ALL & ~E_DEPRECATED & ~E_NOTICE & ~E_STRICT , display_errors = Off , max_execution_time = 600 (600 only for installation process. 30 After (default))
- PHP Modules: curl, gd, imap, mysql

MySQL Requirements:

- Version: 5.x
Pay attention on 5.6 or higher, by default on some distros sql_mode is STRICT. You must check [this](https://dev.mysql.com/doc/refman/5.6/en/server-options.html#option_mysqld_sql-mode) and empty sql_mode.

See you
