### ISSUE TITLE
Administrator User Activation

### ISSUE THREAD

**Issue by capnino** [VTECRM/vtenext#45]
I am frozen on the activation page ...... no way to go ahead.
My advise is to modify the activation policy because suddenly this problem rise also after the first activation bloking the possibility to use the CRM.
Can you help me ?

Ubuntu 16.04 LTS + MariaDb and php 5.6 ....

**Comment by cicalo** [comment]
same problem.

vte 17.10 on vte 17.10

Other issue encountered schemadb xml lenght of two fields  256 chr.
