### ISSUE TITLE
Theme style - css 

### ISSUE THREAD

**Issue by cicalo** [VTECRM/vtenext#46]
I've now complete the installation from scratch. after some issue solved by me reading on internet, now I not able to go on.

Here is my dashboard, also login page was the same....
<img width="960" alt="immagine" src="https://user-images.githubusercontent.com/24680908/36555335-f2402c34-1801-11e8-891b-0c8cfc96a92f.png">

Is there someone who can help me!!

**Comment by denisdal** [comment]
Browser console is telling you something about missing css ?
