### ISSUE TITLE
Forbidden You don't have permission to access /vtenext on this server.

### ISSUE THREAD

**Issue by technadtab** [VTECRM/vtenext#47]
Hi! I'm Nadia from Italy.
First of all sorry for my english.
I'm desperate because are 2 days that I try to instal VTECRM on my server LINUX hosting by Aruba, but 
i can't. I can only see this: Forbidden You don't have permission to access /vtenext on this server.
I have already get the 755 permission to all the an set php to 5.5
Detail of my hosting:
PHP Version | 5.4.16
memory_limit | 512M | 512M
upload_max_filesize | 500M | 500M
GD Support | enabled
GD Version | bundled (2.1.0 compatible)
MYSQL Versione del server: 5.5.59-38.11-log
utf8_general_ci
Please there's someone that con help me?
Thanks in advance
Nadia

**Comment by davidegiarolo** [comment]
Hi Nadia,
have you tried /vtenext/install.php ?looks like your server don't manage the redirect from index.php->install.php that is made by vtenext when you start it from the first time
regards

**Comment by Bogey** [comment]
I have the same problem. It appears it's the .htaccess file and in particular the line:
RewriteRule ^(.*\.(js|css))$ smartoptimizer/?$1

**Comment by Bogey** [comment]
Ok what worked for me editing the virtual host setting:
I changed 
`Options Indexes`
into
`Options FollowSymLinks`

**Comment by technadtab** [comment]
Hi, sorry for the delay in my replay.
Now it's ok and  the configuration start, but whentry to lunch I have the following message: "
Unable to connect to database Server. Invalid SQL Connection Parameters specified"

And the following error:

Strict Standards: Only variables should be assigned by reference in /web/htdocs/www.ecbgroup.it/home/vtenext/source/include/install/resources/utils.php on line 73

I don't really what I have to do. I'm sure that the data insert are all ok
Atached you can find soma screenshot.

Thanks in advance.

Nadia
![cattura a](https://user-images.githubusercontent.com/37345303/38564592-bbfe369a-3cdf-11e8-9383-9e6ef3b58511.JPG)
![catturab](https://user-images.githubusercontent.com/37345303/38564602-c1d0f544-3cdf-11e8-8eff-b48ad270f7a7.JPG)
![cattura c](https://user-images.githubusercontent.com/37345303/38564627-d18b2536-3cdf-11e8-8357-43646bea331a.JPG)

**Comment by denisdal** [comment]
Hi @technadtab 
I suppose that you are using mysql service hosted by Aruba.
In that case you have not the permission to create the database.
Aruba pre-create 5 database to use, grab one free and specify in "Database name" and DON'T flag "Create Database" option.

Regards
