### ISSUE TITLE
VTE 15.05 impossible to set mail server

### ISSUE THREAD

**Issue by SistemistaRCH** [VTECRM/vtenext#48]
When you set a new mail server the only answer you have is "La mail non puo` essere inviata all`amministratore. Verifica le configurazioni del mail server e la email dell`amministratore" it means
"mail cannot send to the administrator. Check the configurations of a mail server and the account of administrator". Whant can we do?

**Comment by denisdal** [comment]
Hi,
that strange VTE version...
Please check that the admin user have same email address that you are trying to set into outgoing email server.
This reduce other possible error scenario..(for example, this help in Exchange env)

Regards
