### ISSUE TITLE
Update from VTECRM 15.05

### ISSUE THREAD

**Issue by Franzkekko** [VTECRM/vtenext#5]
Hi! I tried to write in VTECRM forum but it's impossible, I can't find a way to login after registration (form that I had to dig to find out).

Is it possible to update from VTECRM v15.05 to VTE NEXT? 

Thanks in advance,
Franz

**Comment by davidegiarolo** [comment]
Hi, this is the right place to open issues about VTE.
We are collecting issues about the VTENEXT just released so when is more stable, i suppose 2-4 weeks, we can give the update script that point to a more debugged version. If you want to contribute to update the upgrade script you are welcome

**Comment by Franzkekko** [comment]
Thanks for answering! unfortunately I'm not good at writing code... :( but I'm very good at finding  problems :D 
Will wait for any evolution.
Thanks again

**Comment by cianop** [comment]
Hi, any news about the upgrade script?
Thank you

**Comment by pauceano** [comment]
So, what is the procedure to upgrade the new version. Thanks.

**Comment by andreavergo** [comment]
Hi! Now it's possible upgrade?
