### ISSUE TITLE
Problem with mysql

### ISSUE THREAD

**Issue by gioguadagnini** [VTECRM/vtenext#50]
Hi.
I'm having some problems in the configuration of the CRM. I've installed all php components and set all the configuration of php.ini file like the page suggest me to do. But when I've to connect to mysql database the page show me this error: 
"Unable to connect to database Server. Invalid SQL Connection Parameters specified. 
This may be due to the following reasons:
specified database user, password, hostname, database type, or port is invalid. More Information
specified database user does not have access to connect to the database server from the host".

I've tested the configuration on my server and it works correctly.
I've tried to give the grant to the user but, it doesn't work.
I attach some pictures....
![1](https://user-images.githubusercontent.com/40520854/41810346-36d44e8e-76fd-11e8-95bc-28a96aeb1cce.PNG)
![2](https://user-images.githubusercontent.com/40520854/41810347-3a14a544-76fd-11e8-87d6-5e5d16c64723.PNG) even here i've got one error.
![3](https://user-images.githubusercontent.com/40520854/41810348-3c74df70-76fd-11e8-8109-868090e61bad.PNG)

My test of the port 3306 with telnet.
![prova telnet](https://user-images.githubusercontent.com/40520854/41810354-5a251094-76fd-11e8-9ca3-1891927686f4.PNG)

The users and theirs privileges.
![utenti mysql](https://user-images.githubusercontent.com/40520854/41810390-d2f6df52-76fd-11e8-8aa8-1821703bbfdc.PNG)

Any suggestions???
Thank you.

**Comment by gioguadagnini** [comment]
Ok thank you. Now the DB works.
But when i click 'NEXT' the server show me a white page and seems to have stuck there.

**Comment by denisdal** [comment]
Have you got any errors on php log ?
