### ISSUE TITLE
Fattura Elettronica

### ISSUE THREAD

**Issue by marcozeus** [VTECRM/vtenext#53]
Are VTECRM Nect CE ready for the mandatory 2019 Fattura Elettronica?
If no, do you are planning it?
If yes, how can I use it?
Thank you very much
Regards

**Comment by macasa** [comment]
Purtroppo no. Io ho fatto l'aggiornamento a vte next quest'estate (versione a pagamento di crmvillage), e ora ho un software che emette fatture in un formato che fra due mesi sarà inutilizzabile. Ho chiesto, anche pagando, se esiste un plugin per creare la fattura nel formato xml, mi è stato detto di attendere. Siamo a novembre, a due mesi dalla scadenza dell'obbligo, sollecito e non rispondono.... incredibile. Qualcuno ha trovato una soluzione pratica, senza cambiare software? grazie

**Comment by davidegiarolo** [comment]
hi this platformis a crm+bpm and is not an erp or accountant software. we are integrated with many erp system that are ready for "fattura elettronica". 
if like you said you are a paying customer is suppose that you have better channels than this in order to receive some news.
btw, if you want to make only noise... you're welcome as usual
regards

**Comment by macasa** [comment]
Se sono qui  per chiedere supporto in un forum (e per darne, visto che ho risposto per primo ad una domanda idi altro utente) è perchè attraverso il mio referente presso il fornitore non ho avuto riposte, nonostante i diversi tentativi, e tanta buona volontà. E mi fermo su questo, perchè non sono qui per fare polemica. 
La fatturazione è parte integrante di vte crm, ed e credo sia importante nel processo di vendita, anzi direi fondamentale, quindi la domanda dell'utente era più che legittima. Il software è bellissimo, fa -anche- le fatture, ma consente di creare solo file pdf, che ora vanno bene ma fra due mesi non serviranno più a nulla. Aggiungere un pulsante per creare un xml in alternativa al pdf non mi sembra cosa così complicata da fare, sapendolo con un anno di anticipo, non vedo la necessità di interfacciarsi con un altro software per questo. Poter creare gli xml credo sia veramente il minimo sindacale, per un software che fa -anche- le fatture, venduto nel 2019 in Italia. Mia personale opinione ovviamente. Io confido che un aggiornamento per questo sarà rilasciato ai clienti, ma in assenza di comuniazioni e con la scadenza alle porte valuto possibili soluzioni alternative, magari provvisorie.

**Comment by davidegiarolo** [comment]
Rispondo in italiano per chiarezza, questo forum sarebbe in inglese....
Le fatture sono presenti nel crm per visibilità dello stato di pagamento e informazioni affini. Se si producono con il crm successivamente vanno sincronizzate con il gestionale che appunto fa il suo lavoro: f24, liquidazione iva, e quindi anche fatturazione elettronica.
vtenext non è un gestionale, è un crm+bpm che tramite l'automazione dei processi aziendali semplifica le attività quotidiane, ma la fatturazione elettronica è a nostro avviso compito del gestionale.
Se come dice è cliente potrà contattare l'assistenza commerciale e trovare soluzioni utili al problema imminente della fatturazione elettronica.
Personalmente ho sentito odore di polemica ma come detto in precedenza: se ha un regolare contratto di assistenza ci sono canali dedicati presidiati in maniera più efficace del forum community.
In merito al pulsante "genera xml": ci sono altre considerazioni fiscali in merito, non è un banale output xml che si può realizzare con qualche ora di lavoro.
Se la soluzione proposta non la soddisfa le consiglio in prima persona di valutare soluzioni più affini alle sue esigenze.
In alternativa ribadisco che tramite il supporto commerciale potrà avere una lista di gestionali già integrati con la soluzione (versione business) e quindi potrà gestire in serenità la fatturazione elettronica.
Onde evitarle perdite di tempo le consiglio di menzionare questa conversazione nel nostro portale clienti dedicato all'assistenza per i sottoscrittori della versione business.
a presto  e grazie dell'attenzione

**Comment by marcozeus** [comment]
Mi dispiace di aver creato questa piccola "polemica" che probabilmente nessuno vuole. Ringrazio entrambi per le risposte ma sono sulla stessa linea di pensiero di macasa. 
Uso VTECRM CE da 7 anni sia per una gestione classica CRM e sia per la fatturazione, non ho grandi necessità da ERP o da gestionale classico. 
Non sono una fonte di guadagno per VTECRM, almeno per ora, ma vedrei un adeguamento alla fattrura elettronica come un ennesimo passo importantissimo nello sforzo molto pregevole che la vostra azienda fa in questo campo; almeno per gli utenti ed i clienti italiani.
Se poi, come dice giustamente Davide, la fatturazione elettronica non rientra nei piani di sviluppo del software (in quanto orientato più verso CRM e BPM) ne dovrò prendere atto e cercare soluzioni alternative, mio malgrado. Peccato, perchè VTECRM è veramente un gran bel prodotto.
IMHO

**Comment by macasa** [comment]
Grazie davidegiarolo dell'interessamento. Più che polemica incredulità e disappunto, a dire il vero.
Io scrivo in italiano non per mancanza di rispetto ma perchè il tema è d'interesse prettamente nazionale in questo momento, infatti il titolo è in italiano e comunque se qualche straniero fosse interessato può tradurre automaticamente con il browser senza fatica.
Vede, mi sono anch'io chiesto se vte, così come da voi migliorato e proposto, stava diventando un sw solo per aziende più grandi, quelle dotate di erp e/o altri sw per la contabilità e la gestione. L'ho chiesto al mio referente commerciale in crmvillage, mi è stato risposto "no assolutamente, vogliamo continuare a seguire le piccole imprese come la sua" non "sì in effetti è così, le consiglio di valutare altre soluzioni più affini alle sue esigenze" o qualcosa del genere. Una piccola azienda con vte, fino ad oggi, faceva tranquillamente le fatture  in pdf stampabili a norma di legge (e come dice marcozeus anche con la versione free). Al resto (f24, liquidazione iva ecc.) ci pensa il commercialista, non sono processi gestiti all'interno con certe dimensioni aziendali (io ho un contratto fino a 5 utenti vte). Da gennaio non sarà più possibile e questo è un problema. A meno di raddoppiare il lavoro manuale, che è fuori questione.
Il file xml deve avere requisiti ben precisi, che si conoscono da tempo, ma si può generare in qualsiasi  modo, anche manualmente con un banale editor, per ipotesi. Se conforme, va comunque bene per la fatturazione elettronica. In vte è già stato implementato da altri, mi risulta. Non credo sia tecnicamente complicato.
La fatturazione elettronica non vuole costituire un onere aggiuntivo per le imprese, anzi, il contrario. Invece così rischia di diventarlo, e non da poco. In ogni caso, questo maggior onere, se l'alternativa al pdf non verrà fornita gratuitamente ai clienti, vorrei almeno avere la possibilità di valutarlo, senza dover cambiare il software, che usiamo da anni con soddifazione, anche per molto altro ovviamente. Tenterò un nuovo contatto con il referente commerciale, sperando in miglior fortuna, vediamo se ha qualche soluzione da proporre.
Se qualche utente del forum avesse delle soluzioni alternative da suggerire,gliene sarei grato, anche di carattere provvisorio, ad esempio con estrazione massiva delle fatture in excel per poi generare gli xml sempre massivamente con altra applicazione.
grazie.

**Comment by davidegiarolo** [comment]
@marcozeus nessun problema, è stato uno spunto per discutere, ci mancherebbe. Mi fa piacere che la versione CE ti sia stata utile in questi anni, cerchiamo di diffonderla per rendere semplici le attività quotidiane a chi si relaziona con i clienti cercando appunto di snellire i flussi aziendali. Credo che per la sola fatturazione potrai trovare verticali con tariffe veramente basse che potranno fare al caso tuo, sono certo che per tutta la filiera pre-fattura troverai in vtenext la stessa efficacia che ti ha portato ad usarlo in questi anni. grazie del feedback
@macasa L'invito a scrivere in inglese è dettato dal fatto che il prodotto è distribuito non solo in italia ed anche questo è uno dei motivi che ci spinge a non procedere con l'implementazione della fattura elettronica. Se le specifiche ti sono così chiare, così come la modalità di estrazione tramite xls o altro strumento, perchè non produci un howto/plugin e lo condividi con la community? c'è sempre spazio per i contributi, te ne saremmo tutti grati. Meglio ancora se riesci a recuperare informazioni da chi ti risulta lo abbia già fatto, anzi magari lo convinci a condividerlo con tutti. In alternativa consiglio anche a te di valutare un verticale per la sola fatturazione, magari fra quelli integrati con la nostra soluzione. grazie dell'attenzione

**Comment by macasa** [comment]
@davidegiarolo , sapere che non intedete rendere disponibile la creazione di file utilizzabili è già una notizia. Pessima, inaspettata, ma almeno uno lo sa, meglio tardi che mai, grazie.
Purtroppo non sono uno sviluppatore, altrimenti lo avrei fatto volentieri. Le specifiche non sono chiare solo a me, sono opinioni diffuse di tecnici, si trovano in rete. La mia esperienza indiretta su altri software comunque conferma queste opinioni, non stiamo parlando di niente di difficile o incerto, per fortuna, almeno quello. I problemi sono altri sulla fatturazione elettronica, non riguardano il file xml.
Per risponderti, cercando su google ho visto che è stato creato questo https://www.opencrmitalia.com/blog/fatturazione-elettronica-con-vtiger.html che consente sia di creare i file xml e inviarli ad un provider gratuito, sia di acquistare l'integrazione con un servizio a pagamento. E' esattamente quanto mi aspettavo, servizio base per usare il provider preferito (magari quello pubblico che è gratuito), e in opzione integrazione con servizio a pagamento. Dato che voi non intendete fare qualcosa del genere, posso acquistare questo (o altro simile se esiste) e implementarlo sulla mia installazione vte next? E' compatibile? Da quanto dici, voi proponete delle alternative per integrazione con servizi a pagamento, spero finalmente di conoscerle dal referente commerciale e poter valutare. Grazie

**Comment by macasa** [comment]
@marcozeus ho avuto risposta da operncrmitalia che nel frattempo ho interpellato, purtroppo la loro soluzione che avevo linkato sopra non è compatibile, essendo sviluppata su vtiger 7 mentre vte - ho appreso- è derivata da vtiger 5 e non più tenuta allineata alle successive. Sono perciò ancora alla ricerca di una soluzione.

**Comment by marcozeus** [comment]
@macasa grazie per il premuroso aggiornamento, anche io sto guardando in giro.

**Comment by davidegiarolo** [comment]
effettivamente la loro soluzione per vtiger non è compatibile con vtenext, sono passati ormai 10 anni dal fork ovvero momento in cui abbiamo iniziato a sviluppare quello che per noi era importante e primario in termini di prodotto. credo che potresti provare a recuperare parte del lavoro da loro fatto ed adattarlo alla nostra versione community. open source permette questo approccio, fortunatamente. 
facci sapere come procede! 
un buon lavoro

**Comment by davidegiarolo** [comment]
dimenticavo di riportare per comodità la lista di alcuni dei gestionali già integrati con vtenext Business:
Nts Business, Passepartout Mexal, Team System Aliante e Gamma, Zucchetti Ad hoc e Mago.
