### ISSUE TITLE
Impossibile accedere

### ISSUE THREAD

**Issue by adroma** [VTECRM/vtenext#54]
Improvvisamente non mi è più possibile accedere.
Ripristino la password tramite e-mail, ma nonostante questo continua a respingermi l'accesso.
Da database potrei forzare il cambiamento della password?
Grazie

**Comment by adroma** [comment]
Una community molto attiva!

**Comment by davidegiarolo** [comment]
salve adroma,
la community offre servizio gratuito di supporto e non sono garantiti tempi di risposta come nei normali contratti di assistenza.
Servirebbe maggiore dettaglio in merito al problema. Ad esempio tipo di installazione, server di posta in uso, tipologia di errore.
Altrimenti con i dettagli attuali risulta difficile supportarla
buona serata
