### ISSUE TITLE
Problemi accesso VTE

### ISSUE THREAD

**Issue by SIlviaKik** [VTECRM/vtenext#56]
Buongiorno,
da due giorni in fase di accesso a VTE mi segnala l'errore
"VTECRM network service fails to create you license (err. 5 )"

Ho provato a caricare nuovamente le credenziali di administrator ma non riesce ad autenticare la licenza.
Mi sapete dire come risolvere il problema?

Grazie

**Comment by davidegiarolo** [comment]
Salve, puoi indicarci la versione in uso e se il server che la ospita ha connettività verso internet?
