### ISSUE TITLE
Creazione modulo

### ISSUE THREAD

**Issue by eptanord** [VTECRM/vtenext#58]
Buongiorno,
quando creo un modulo, se tento d'installarlo, appare il messaggio il messaggio che è in corso l'installazione, ma di fatto non si installa.
Cosa sbaglio? Come posso risolvere? Sto usando vtenext-17.07

Grazie

**Comment by davidegiarolo** [comment]
ciao, hai verificato i permessi di scrittura nelle cartelle? Durante l'installazione del modulo vengono copiati alcuni files e quindi devi assicurarti che l'utente webserver (non hai indicato quale utilizzi) abbia i corretti privilegi

**Comment by eptanord** [comment]
Ho provato a settare la cartella con i permessi 777 con l'utente www-data, ma il risultato è lo stesso.
Devi ricreare i moduli dopo questa modifica?

**Comment by eptanord** [comment]
> ciao, hai verificato i permessi di scrittura nelle cartelle? Durante l'installazione del modulo vengono copiati alcuni files e quindi devi assicurarti che l'utente webserver (non hai indicato quale utilizzi) abbia i corretti privilegi

Ho provato a settare la cartella con i permessi 777 con l'utente www-data, ma il risultato è lo stesso.
Devi ricreare i moduli dopo questa modifica?

**Comment by eptanord** [comment]
Alla termine del Wizard di creazione modulo appare questo messaggio all'inizio della pagina:

Warning: file_get_contents(storage/custom_modules/modmaker_7_ModuloTest/ModuloTest.php): failed to open stream: No such file or directory in /var/www/html/vte/modules/Settings/ModuleMaker/ModuleMakerGenerator.php on line 1010

**Comment by eptanord** [comment]
Ho rieffettuato la reinstallazione di un altro VTE, ma il problema persiste. E' un problema delle versione community?

**Comment by orolez** [comment]
Buongiorno ho il medesimo problema con VTE19CE. Ho controllato i permessi, ma non riesco a installare il modulo CUSTOM. Qualche suggerimento ?
