### ISSUE TITLE
Duplicazione elementi

### ISSUE THREAD

**Issue by eptanord** [VTECRM/vtenext#59]
Buongiorno, c'è la possibilità di duplicare gli elementi (aziende, contatti, oridni, ecc...) in VTE?
Non ho trovato questa funzione.

**Comment by davidegiarolo** [comment]
Puoi duplicare gli elementi tramite il pulsante altro in alto a destra. Lo trovi all'interno delle schede di dettaglio

**Comment by eptanord** [comment]
Grazie mille!!
