### ISSUE TITLE
Cron job

### ISSUE THREAD

**Issue by yvesmarieTM** [VTECRM/vtenext#6]
Hi,

Congratulations for your software. I tried a lot of crm ; yours is very efficient.
I have a problem to execute cron job : "access denied" in the cron.log

The cron job is 
"sh /home/.../source/cron/RunCron.sh >> /home/.../source/logs/cron.log 2>&1 "

Thank you for your help.

Yves-Marie

**Comment by denisdal** [comment]
Hi Yves-Marie,
RunCron.sh have execute permission ?

**Comment by denisdal** [comment]
Did you solve the issue ?

**Comment by yvesmarieTM** [comment]
Hi Denis,

No.

Permissions are OK. For example, scan mail manual work’s fine. But, I can’t run scan automatically


Yves-Marie Malphettes
	
Transplis Metalex
12-14 Chemin de la Prairie
93360 Neuilly-Plaisance
Tél : 01 43 00 80 81
Fax : 01 43 00 09 13

**Comment by denisdal** [comment]
Do you refer to Mail scanner job ?
If yes, by default, this job is not active.
To enable it, just execute the query below on your preferred mysql client:
`UPDATE vte_cronjobs SET active=1 WHERE cronname='MailScanner';`

**Comment by yvesmarieTM** [comment]
Hi,

I solved my problem : I run cron task by php-cli, not by sh.

I also updated table « vte_cronjobs »

Thank you.



Yves-Marie Malphettes
	
Transplis Metalex
12-14 Chemin de la Prairie
93360 Neuilly-Plaisance
Tél : 01 43 00 80 81
Fax : 01 43 00 09 13
