### ISSUE TITLE
[solved] Template error after CronJob VTENEXT 18.05

### ISSUE THREAD

**Issue by gillustrazione93** [VTECRM/vtenext#62]
After the CronJob is executed, the VTE loses the template. To restore, I replace all the files with a backup, but after the CronJob is executed, the same error occurs again.
How can you solve?

Dopo l'esecuzione del CronJob il VTE perde il template. Per ripristinare sostituisco tutti i file con un backup ma dopo l'eseuzione del CronJob si ripresenta lo stesso errore.
Come si può risolvere?

![image](https://user-images.githubusercontent.com/34746659/52725855-47650e00-2fb2-11e9-9c85-801f33cad9ab.png)

**Comment by gillustrazione93** [comment]
I isolated the process that causes the problem.
cron/Cleaner.service.php

ho isolato il processo che provoca il problema. 
cron/Cleaner.service.php

**Comment by manueltag** [comment]
Hi @gillustrazione93!

- What operating system are you using?
- What version of PHP are you using?
- Do you enable apache2 mod_rewrite?
- Do you rename htaccess.txt to .htaccess in the root directory?

**Comment by gillustrazione93** [comment]
@manueltag 
OS debian
php 7.0
mod_rewite is ok
i have rename .htaccess

**Comment by manueltag** [comment]
Do you see errors if you open your browser console?

Il giorno Mer 13 Feb 2019, 18:27 gillustrazione93 <notifications@github.com>
ha scritto:

**Comment by gillustrazione93** [comment]
yes

[log_error_chrome.log](https://github.com/VTECRM/vtenext/files/2861480/log_error_chrome.log)

**Comment by manueltag** [comment]
It seems to be an apache error or wrong privileges of crm files (403
Forbidden). Check it please.

Il giorno Mer 13 Feb 2019, 18:44 gillustrazione93 <notifications@github.com>
ha scritto:

**Comment by gillustrazione93** [comment]
I solved the problem by correcting the apache2 directives. I deleted the rule highlighted in the image.

![image](https://user-images.githubusercontent.com/34746659/52775223-71b0dd00-303f-11e9-9919-36788b6eb61b.png)
