### ISSUE TITLE
PHP Fatal error on new installation

### ISSUE THREAD

**Issue by moodino** [VTECRM/vtenext#7]
Hello and sorry for my dusted english but,
when i try to install vte-next on my ubuntu server i got this PHP error:
`Fatal error: Call to a member function GetRowAssoc() on boolean in /mfcrm/include/database/PearDatabase.php on line 1079`
I've also tried on hosting service (register.it and aruba.it) but i've the same fatal error. 
I've googled for solution but i was not lucky. 
can you help me about this?

Tnx in advance

**Comment by manuelemaporti** [comment]
Hi, which ubuntu version are you using?

**Comment by moodino** [comment]
Hi Manuele,
16.04 LTS... but i've also tried on hosting service (with LAMP). I've also tried on my laptop with WinLAMP.
Same results

**Comment by denisdal** [comment]
Are you sure to met the php version requirement ?
Ubuntu 16.04 should came with php 7 and is not supported yet.

**Comment by denisdal** [comment]
Could you please activate query's debug ?
To do this, open config.inc.php and set to true (boolean) `$dbconfig['db_dieOnError']`

**Comment by moodino** [comment]
i have set `$dbconfig['db_dieOnError']` to true, but no changes

**Comment by moodino** [comment]
Any other ideas?

**Comment by manuelemaporti** [comment]
Try with this procedure:
1) download again the source in your server
2) start the installation:
![image](https://user-images.githubusercontent.com/29864701/29872283-43eebed6-8d8f-11e7-8555-0874b3c694ed.png)
3) proceed with the wizard unitl this step:
![image](https://user-images.githubusercontent.com/29864701/29872383-af815b5e-8d8f-11e7-8b89-00d76a7eab19.png)
4) now the file config.inc.php has been created and you can set:
`$dbconfig['db_dieOnError'] = true;`
5) proceed with the wizard

In this way when there is a fatal error because of a query vte print a log with more info.

**Comment by moodino** [comment]
No way... i've lost hope.

**Comment by moodino** [comment]
Ok i've tried in this way:
in /include/database/PearDatabase.php on line 125 i've set to "true" and now i see the error.

`Query Failed => 
:SELECT COALESCE(tbl_s_menu_areas.areaid,-1) AS areaid, tbl_s_areas.area, vte_tab.tabid, vte_tab.name, tbl_s_areas.sequence, tbl_s_menu_areas.sequence FROM vte_tab INNER JOIN (SELECT DISTINCT tabid FROM vte_parenttabrel) parenttabrel ON parenttabrel.tabid = vte_tab.tabid LEFT JOIN tbl_s_menu_areas ON vte_tab.tabid = tbl_s_menu_areas.tabid AND tbl_s_menu_areas.userid = 1 LEFT JOIN tbl_s_areas ON tbl_s_menu_areas.areaid = tbl_s_areas.areaid AND tbl_s_areas.userid = 1 WHERE vte_tab.presence = 0 ORDER BY COALESCE(tbl_s_areas.sequence,999), COALESCE(tbl_s_menu_areas.sequence,999)::
ADODB error => 
[1146] Table 'crmf.tbl_s_menu_areas' doesn't exist`

**Comment by moodino** [comment]
In DatabaseSchema.xml is not included the table "tbl_s_menu_areas"

**Comment by moodino** [comment]
No solution?

**Comment by manuelemaporti** [comment]
That table was installed after the DatabaseSchema. Do you have check php logs?
Try these steps:
- delete the cache of the browser
- set in php.ini 
`display_errors = On`
and
`error_reporting = E_ALL & ~E_DEPRECATED & ~E_NOTICE`
- restart apache
- than retry the installation (with the same configuration in the config.inc.php described in my comment of 30/08)

**Comment by moodino** [comment]
`
Fatal error: Call to a member function addLink() on boolean in /crmvte/modules/ModComments/ModComments.php on line 103`

**Comment by officinainformatica** [comment]
I have the same error:

array (
  0 => 
  array (
    'file' => '\\include\\database\\PearDatabase.php',
    'line' => 595,
    'function' => 'checkError',
  ),
  1 => 
  array (
    'file' => '\\modules\\Area\\Area.php',
    'line' => 424,
    'function' => 'pquery',
  ),
  2 => 
  array (
    'file' => '\\include\\utils\\PageHeader.php',
    'line' => 169,
    'function' => 'getModuleList',
  ),
  3 => 
  array (
    'file' => '\\include\\utils\\PageHeader.php',
    'line' => 41,
    'function' => 'setAreasVars',
  ),
  4 => 
  array (
    'file' => '\\modules\\VteCore\\header.php',
    'line' => 24,
    'function' => 'displayHeader',
  ),
  5 => 
  array (
    'file' => '\\index.php',
    'line' => 812,
    'function' => 'include',
  ),
)


Query Failed =>
:SELECT COALESCE(tbl_s_menu_areas.areaid,-1) AS areaid, tbl_s_areas.area, vte_tab.tabid, vte_tab.name, tbl_s_areas.sequence, tbl_s_menu_areas.sequence FROM vte_tab INNER JOIN (SELECT DISTINCT tabid FROM vte_parenttabrel) parenttabrel ON parenttabrel.tabid = vte_tab.tabid LEFT JOIN tbl_s_menu_areas ON vte_tab.tabid = tbl_s_menu_areas.tabid AND tbl_s_menu_areas.userid = 1 LEFT JOIN tbl_s_areas ON tbl_s_menu_areas.areaid = tbl_s_areas.areaid AND tbl_s_areas.userid = 1 WHERE vte_tab.presence = 0 ORDER BY COALESCE(tbl_s_areas.sequence,999), COALESCE(tbl_s_menu_areas.sequence,999)::
ADODB error =>
[1146] Table 'h461888_crm.tbl_s_menu_areas' doesn't exist

Solution??
