### ISSUE TITLE
Cron Job on Windows not workin

### ISSUE THREAD

**Issue by lorebarita** [VTECRM/vtenext#71]
Your instructions on windows: http://usermanual.vtenext.com/books/manuale-vtenext-1812/page/21-cronjob-%E2%80%93-processi-da-pianificare are not working.
Always gives errors and its not possible to Sync when using scheduler.

**Comment by davidegiarolo** [comment]
Please refer to the content in the readme that comes with the windows installer, we will update asap also the usermanual thank you for your feedback. Here part of the readme:
To register the scheduled task:

SchTasks /Create /SC MINUTE /mo 5 /TN “Scheduled vtenext19ce tasks” /TR “c:\vtenext19ce\htdocs\cron\RunCron.bat” /RU SYSTEM

To unregister it:

SchTasks /Delete /TN “Scheduled vtenext19ce tasks”

**Comment by lorebarita** [comment]
Thank you it works.
