### ISSUE TITLE
Vtenext19ce upgrade

### ISSUE THREAD

**Issue by Jodynet** [VTECRM/vtenext#72]
Vorrei sapere come aggiornare dalla versione 18ce alle 19ce.
How can i upgrade vtenext18ce to 19ce.
Grazie/Thanks

**Comment by davidegiarolo** [comment]
Hi please refer to this guide
http://usermanual.vtenext.com/books/community/page/update-vtenext-from-18ce-to-19ce
Starting from 19ce the software have automatic updates, for the prior version you have to activate them following the guide just linked
regards
