### ISSUE TITLE
Convert Lead

### ISSUE THREAD

**Issue by yvesmarieTM** [VTECRM/vtenext#8]
Hi,

In the QuickStart Guide, you explain "To convert a lead click on the green button: Other -> Convert Lead"
I have no "Convert Lead" in this menu. I have only : "delete" "mass edit" "mail"...

![capture d ecran 2017-08-25 a 15 21 23](https://user-images.githubusercontent.com/29302656/29715802-1c8a7e50-89a9-11e7-9de1-3358a7ed9e76.png)

Yves-Marie

**Comment by manuelemaporti** [comment]
Hello, the button is in the detail view.
![image](https://user-images.githubusercontent.com/29864701/29871861-a19fbd66-8d8d-11e7-82fb-2c2e650a6761.png)

**Comment by davidegiarolo** [comment]
we mean that you can only convert one lead at time, because we suppose you also need to fill up info about the Potential related.
do you think it can be a good a idea to add mass lead convertion?
