### ISSUE TITLE
VTENEXT 19.10 CUSTOMER PORTAL

### ISSUE THREAD

**Issue by maximegti** [VTECRM/vtenext#80]
Salve a tutti. C'è qualcosa di particolare da fare per abilitare il Customer Portal? 
Nella scheda del cliente ho flaggato la voce "utente del portale"; al cliente è correttamente arrivata la mail con credenziali e link per accedere al customer portal, ma la pagina non è raggiungibile.
Anche da locale, accedendo a http://ipvtenetx:8019/portal la pagina non risulta raggiungibile. Grazie

**Comment by maximegti** [comment]
Dopo mille sbattimenti di testa mi sono reso conto che c'è un errore nella mail che vtenext invia ai contatti: il link al customer portal riporta la porta 8019, mentre quella realmente utilizzata dal sistema è la 8419! Spero possa essere d'aiuto a qualcuno...

**Comment by davidegiarolo** [comment]
grazie del debug! prepariamo la patch e la includiamo nei prossimi aggiornamenti OTA

**Comment by davidegiarolo** [comment]
confermi che stiamo parlando della versione autoinstallante per windows?

**Comment by maximegti** [comment]
Si Davide, scusa non avevo visto la tua domanda, parlo della versione autoinstallante per Windows
