### ISSUE TITLE
problema cambio password

### ISSUE THREAD

**Issue by gdemartinez** [VTECRM/vtenext#9]
Ciao a tutti,
da qualche giorno se provo a collegarmi come utente admin, viene visualizzato il messaggio che la password va cambiata. Clicco su "forgot password", mi arriva correttamente il link via mail per cambiarla, ma nel momento in cui specifico una nuova password, viene visualizzato il seguente messaggio d'errore: Connection with VTECRM Network failed (error).
Qualcuno ha qualche suggerimento?

**Comment by manuelemaporti** [comment]
Hello, I think that you are using the old version of community edition of vtecrm. That version needs the connection to internet in order to recover the password.

**Comment by gdemartinez** [comment]
The server is connected to the internet, the version is 15.10 and is the first time that it's ask me to change the password.

**Comment by davidegiarolo** [comment]
this forum is related to the vtenext, the version you are using is an old one. can you download from here and try to install it?
